### ISSUE TITLE
BonfireWarpParam crash saving (elden ring 1.07)

### ISSUE THREAD

**Issue by CristianPi** [soulsmods/DSMapStudio#205]
```bash

Crash caught : Remaining size of stream was smaller than requested number of bytes.
Stack Trace :    at SoulsFormats.BinaryReaderEx.ReadBytes(Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 276
   at SoulsFormats.BinaryReaderEx.GetBytes(Int64 offset, Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 306
   at SoulsFormats.BinderFileHeader.ReadFileData(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BinderFileHeader.cs:line 172
   at SoulsFormats.BND4.Read(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BND4\BND4.cs:line 87
   at SoulsFormats.SoulsFile`1.Read(Byte[] bytes) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\SoulsFile.cs:line 72
   at SoulsFormats.SFUtil.DecryptERRegulation(String path) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\SFUtil.cs:line 529
   at StudioCore.ParamEditor.ParamBank.SaveParamsER(Boolean partial) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1127
   at StudioCore.ParamEditor.ParamBank.SaveParams(Boolean loose, Boolean partialParams) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1188
   at StudioCore.ParamEditor.ParamEditorScreen.SaveAll() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamEditorScreen.cs:line 1134
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 731
   at StudioCore.MapStudioNew.Run() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 323
   at DSMapStudio.Program.Main(String[] args)
Runtime terminating: True
Unhandled exception. System.IO.EndOfStreamException: Remaining size of stream was smaller than requested number of bytes.
   at SoulsFormats.BinaryReaderEx.ReadBytes(Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 276
   at SoulsFormats.BinaryReaderEx.GetBytes(Int64 offset, Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 306
   at SoulsFormats.BinderFileHeader.ReadFileData(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BinderFileHeader.cs:line 172
   at SoulsFormats.BND4.Read(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BND4\BND4.cs:line 87
   at SoulsFormats.SoulsFile`1.Read(Byte[] bytes) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\SoulsFile.cs:line 72
   at SoulsFormats.SFUtil.DecryptERRegulation(String path) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\SFUtil.cs:line 529
   at StudioCore.ParamEditor.ParamBank.SaveParamsER(Boolean partial) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1127
   at StudioCore.ParamEditor.ParamBank.SaveParams(Boolean loose, Boolean partialParams) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1188
   at StudioCore.ParamEditor.ParamEditorScreen.SaveAll() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamEditorScreen.cs:line 1134
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 731
   at StudioCore.MapStudioNew.Run() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 323
   at DSMapStudio.Program.Main(String[] args)

```
I'm mass editing BonfireWarpParam setting all(most) every grace 

```
selection : eventflagId: = 71801
```

Saving the project -> crash

[edited regulation.bin](https://drive.google.com/file/d/1YNOWJhRcmRAb5--ZlpdCmV4-_Lvhjk3t/view?usp=sharing)
[original mod trying to edit regulation.bin](https://drive.google.com/file/d/1cVyk61E0Tb909w9nPQkpEle0hzKVPwgm/view?usp=sharing)

elden ring 1.07
[release-1.04](https://github.com/soulsmods/DSMapStudio/releases/tag/release-1.04)

**Comment by kingborehaha** [comment]
Can't replicate. Does your targeted game folder have 1.07 regulation?

**Comment by CristianPi** [comment]
Mmm strange, when I have time I will try step by step and leave
instructions.

For now i managed to modify the file with yapped (bit of a pain to modify
lots of lines).

Yes regulation.bin is inside the main folder otherwise the program crash at
startup.

**Comment by kingborehaha** [comment]
Is the regulation.bin inside of the Game folder version 1.07, or could it possibly be an older version?
