### ISSUE TITLE
"No Physical Devices Exist" error on launch. 

### ISSUE THREAD

**Issue by Indeciiissive** [soulsmods/DSMapStudio#483]
New to modding, Ive already installed .NET 7 Desktop runtime and .NET 7 ASP.NET core runtime

DSMapStudio Version 1.08.0
No physical devices exist.
   at Veldrid.Vk.VkGraphicsDevice.CreatePhysicalDevice() in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 645
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 127
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\GraphicsDevice.cs:line 853
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 189
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 173
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 105
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 40
   at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 114
   at DSMapStudio.Program.Main(String[] args)

**Comment by kingborehaha** [comment]
Do you have integrated graphics alongside a graphics card? If so, try disabling integrated graphics in device manager.

**Comment by RiadhAdrani** [comment]
Hello @kingborehaha,
what if I don't have an integrated GPU ?

thanks.

**Comment by katalash** [comment]
What GPU do you have and are your drivers up to date?

**Comment by RiadhAdrani** [comment]
@katalash updating the GPU driver worked, thanks. But I think you should contribution guide some where.

**Comment by Indeciiissive** [comment]
It was integrated graphics causing the issue. However, disabling integrated graphics distorted my resolution, so I found a workaround by going into NVIDIA control panel and forcing the program to use the GPU instead.

**Comment by katalash** [comment]
Huh that's strange. I've been trying to get the initialization code right so that dedicated GPUs are always selected but in that case there should be some physical devices to select. I've modified it more since the last release so hopefully it may work better in the future?

**Comment by MaximKurganovich** [comment]
Hi! I have the same problem, but changing the graphics processor did not help. What else can I try?

**Comment by MaximKurganovich** [comment]
It helped me update the drivers

**Comment by RulzCZhero** [comment]
Hi, I'm having the same issue and I tried updating my drivers, used NVIDIA control panel to force it to use the correct GPU and even disabled my integrated graphics. Is there any other thing I could try?

**Comment by kingborehaha** [comment]
Closing this since it's hard to tell if these issues are still relevant in the newest releases of DSMapStudio (as some of the code involved may have been changed). If anybody continues to have this error in the latest release of DSMS, please open a new issue.
