### ISSUE TITLE
How do i fix this error.

### ISSUE THREAD

**Issue by OFU461347** [soulsmods/DSMapStudio#489]
I opened a program today, and it said this:
--------------------------
DSMapStudio Version 1.08.0
'0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at StudioCore.Editor.ProjectSettings.Deserialize(String path) in D:\a\DSMapStudio\DSMapStudio\StudioCore\Editor\ProjectSettings.cs:line 52
   at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 167
   at DSMapStudio.Program.Main(String[] args)
----------------------

'0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

--------------------------------------
![image](https://github.com/soulsmods/DSMapStudio/assets/89918984/8b7302de-95c1-46ea-865b-275d48ca6028)

It was usable before. and I don't know why it happened.

**Comment by kingborehaha** [comment]
It looks like your project.json was corrupted, which can be found in your project folder. Delete it and create a new project.

**Comment by OFU461347** [comment]
> It looks like your project.json was corrupted, which can be found in your project folder. Delete it and create a new project.
