### ISSUE TITLE
"Remaining size of stream was smaller than requested number of bytes." (DSR)

### ISSUE THREAD

**Issue by capra-kid** [soulsmods/DSMapStudio#498]
Can't believe I made a github account just to post this but searching for this issue online has been fruitless. I'm trying to create a new project in DSMapStudio. Every time I do, I get this same error log. No idea what any of it means 😅

**DSMapStudio Version 1.08.0
Remaining size of stream was smaller than requested number of bytes.
   at SoulsFormats.BinaryReaderEx.ReadBytes(Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 276
   at SoulsFormats.BinaryReaderEx.GetBytes(Int64 offset, Int32 count) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\BinaryReaderEx.cs:line 304
   at SoulsFormats.BinderFileHeader.ReadFileData(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BinderFileHeader.cs:line 169
   at SoulsFormats.BND3.Read(BinaryReaderEx br) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Binder\BND3\BND3.cs:line 71
   at SoulsFormats.SoulsFile`1.Read(String path) in D:\a\DSMapStudio\DSMapStudio\SoulsFormats\SoulsFormats\Util\SoulsFile.cs:line 86
   at StudioCore.ParamEditor.ParamBank.SaveParamsDS1R() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1044
   at StudioCore.ParamEditor.ParamBank.SaveParams(Boolean loose, Boolean partialParams) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 1410
   at StudioCore.ParamEditor.ParamEditorScreen.SaveAll() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamEditorScreen.cs:line 1352
   at StudioCore.MapStudioNew.AttemptSaveOnCrash() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 647
   at DSMapStudio.Program.Main(String[] args)**

**Comment by capra-kid** [comment]
Validating the files worked, thanks! 😎
