### ISSUE TITLE
The program crashes when I try to modify any value.  (DS1Remastered)

### ISSUE THREAD

**Issue by LuisAngelGR** [soulsmods/DSMapStudio#698]
The program starts correctly, I can load the maps, I can create projects, save them and load them.
The problem starts when I want to modify any parameter of the game, the program crashes instantly.
I have already tried to run it as administrator, changing the game location and it didn't work.
Thanks. :)

Crash Log:

DSMapStudio Version 1.08.2

Non-static method requires a target.

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at StudioCore.MsbEditor.MultipleEntityPropertyChangeAction..ctor(PropertyInfo prop, HashSet`1 changedEnts, Object newval, Int32 index, Int32 classIndex) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\Action.cs:line 254
   at StudioCore.MsbEditor.PropertyEditor.ChangePropertyMultiple(Object prop, HashSet`1 ents, Object newval, Boolean& committed, Int32 arrayindex, Int32 classIndex) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\PropertyEditor.cs:line 442
   at StudioCore.MsbEditor.PropertyEditor.UpdateProperty(Object prop, HashSet`1 selection, Object newval, Boolean changed, Boolean committed, Int32 arrayindex, Int32 classIndex) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\PropertyEditor.cs:line 402
   at StudioCore.MsbEditor.PropertyEditor.PropEditorGeneric(Selection selection, HashSet`1 entSelection, Object target, Boolean decorate, Int32 classIndex) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\PropertyEditor.cs:line 1009
   at StudioCore.MsbEditor.PropertyEditor.PropEditorGeneric(Selection selection, HashSet`1 entSelection, Object target, Boolean decorate, Int32 classIndex) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\PropertyEditor.cs:line 1009
   at StudioCore.MsbEditor.PropertyEditor.OnGui(Selection selection, String id, Single w, Single h) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\PropertyEditor.cs:line 1059
   at StudioCore.MsbEditor.ModelEditorScreen.OnGUI() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MsbEditor\ModelEditorScreen.cs:line 257
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 1411
   at StudioCore.MapStudioNew.Run() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 328
   at DSMapStudio.Program.Main(String[] args)

**Comment by Philiquaz** [comment]
Looks to be msb related...
When you mean to change a field, what field are you changing? Is it perhaps a specific field or object type that's struggling to be edited?
Are you selecting multiple entities to edit?

**Comment by kingborehaha** [comment]
It looks like you're changing fields within the model editor, which is unsupported ATM (and really should be dulled out for the time being)

**Comment by LuisAngelGR** [comment]
yeah, you're right. I unintentionally focused only on the model editor, as that's where my interest lies and what my question is based on. I didn't see anything that said the model editor didn't work,  I probably missed something ?  Thx a lot!
