### ISSUE TITLE
[1.09.1] Crash when saving lights (BTL) in Dark Souls 3

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#763]
**Steps to reproduce:**
1. Open a Dark Souls 3 project
2. Load any map (I only tested m30_01 (Lothric Castel) and m40 (Firelink))
3. Modify any light (e.g. move a point light a tiny bit)
4. Ctrl+S
5. Crash

Upon crashing, the following error message appears:
![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/a08af0d5-6d1b-4bcc-9eb5-012daf8b7125)

Crash log:
```
DSMapStudio Version 1.09.1

Asset path did not start with game or project directory: C:\mods\DS3\DSMapStudio-1.06\projects\recovery\09-11-2023-(05-28-25)\map\m30_01_00_00\m30_01_00_00_0000.btl.dcx

   at StudioCore.Utils.GetLocalAssetPath(AssetLocator assetLocator, String assetPath) in ./StudioCore/Utils.cs:line 260
   at StudioCore.MsbEditor.Universe.SaveBTL(Map map) in ./StudioCore/MsbEditor/Universe.cs:line 1324
   at StudioCore.MsbEditor.Universe.SaveMap(Map map) in ./StudioCore/MsbEditor/Universe.cs:line 1333
   at StudioCore.MsbEditor.Universe.SaveAllMaps() in ./StudioCore/MsbEditor/Universe.cs:line 1461
   at StudioCore.MsbEditor.MsbEditorScreen.SaveAll() in ./StudioCore/MsbEditor/MsbEditorScreen.cs:line 1237
   at StudioCore.MapStudioNew.SaveAll() in ./StudioCore/MapStudioNew.cs:line 579
   at StudioCore.MapStudioNew.AttemptSaveOnCrash() in ./StudioCore/MapStudioNew.cs:line 611
   at DSMapStudio.Program.Main(String[]) in ./DSMapStudio/Program.cs:line 40
```

---

This bug is specific to 1.09.1. Doing the same thing in 1.09.0 works perfectly fine.

**Comment by Philiquaz** [comment]
Fixed in the hotfix releases.
