### ISSUE TITLE
Crashes when i click "load map". Low requirements exe, DSR.

### ISSUE THREAD

**Issue by DoctorMaleChicken** [soulsmods/DSMapStudio#765]
Crash log: 

DSMapStudio Version 1.09.1

Object reference not set to an instance of an object.

   at StudioCore.Scene.DebugPrimitiveRenderableProxy.GetBoxRegionProxy(RenderScene scene) in ./StudioCore/Scene/RenderableProxy.cs:line 1366
   at StudioCore.MsbEditor.Universe.GetRegionDrawable(Map map, Entity obj) in ./StudioCore/MsbEditor/Universe.cs:line 154
   at StudioCore.MsbEditor.MapEntity.UpdateRenderModel() in ./StudioCore/MsbEditor/Entity.cs:line 1218
   at StudioCore.MsbEditor.Entity.AddChild(Entity child) in ./StudioCore/MsbEditor/Entity.cs:line 174
   at StudioCore.MsbEditor.Map.LoadMSB(IMsb msb) in ./StudioCore/MsbEditor/ObjectContainer.cs:line 246
   at StudioCore.MsbEditor.Universe.LoadMapAsync(String mapid, Boolean selectOnLoad) in ./StudioCore/MsbEditor/Universe.cs:line 723
   at StudioCore.MsbEditor.MsbEditorScreen.Update(Single dt) in ./StudioCore/MsbEditor/MsbEditorScreen.cs:line 127
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in ./StudioCore/MapStudioNew.cs:line 703
   at StudioCore.MapStudioNew.Run() in ./StudioCore/MapStudioNew.cs:line 274
   at DSMapStudio_LowRequirements.Program.Main(String[]) in ./DSMapStudio_LowRequirements/Program.cs:line 35

**Comment by Philiquaz** [comment]
The map editor isn't supported on the low requirements exe. The purpose of that executable is to not use advanced graphical functions, letting users access the param and text editors if they are unable to run the vulkan required for the regular executable.

**Comment by DoctorMaleChicken** [comment]
damn.......
