### ISSUE TITLE
Param file not found

### ISSUE THREAD

**Issue by pinkisdead** [soulsmods/DSMapStudio#811]
![image](https://github.com/soulsmods/DSMapStudio/assets/95844665/3718c079-7e8f-4628-a8fb-99320671bb5f)
![image](https://github.com/soulsmods/DSMapStudio/assets/95844665/b892d7b6-460e-44d0-b0a0-7dcc65604568)
This is a fresh install of Elden Ring and I dont know why this is happening when it was running perfectly fine before.
How can I fix this crash because I've tried unpacking, I've tried reinstalling, the game is running perfectly fine with no issues

Crash Log
DSMapStudio Version 1.10.0

Cannot locate param files for EldenRing.
Your game folder may be missing game files, please verify game files through steam to restore them.

   at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in ./src/StudioCore/ParamEditor/ParamBank.cs:line 866
   at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass73_0.<ReloadParams>b__0() in ./src/StudioCore/ParamEditor/ParamBank.cs:line 1012
   at StudioCore.Editor.TaskManager.LiveTask.<CreateTask>b__15_0() in ./src/StudioCore/Editor/TaskManager.cs:line 183
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )

**Comment by Philiquaz** [comment]
You don't have the param files in the game folder. Unpacking the game won't redownload regulation.bin to your game folder.
Verify the game files using steam as it says. Ensure the file appears in the game folder.

I can only tell you what this error message means - that regulation.bin is not found in the folder that mapstudio is told is the game folder.
I expect the game functions fine because you may be using modengine, which will load from another directory anyway.

In your reinstall process, did you reinstall to a different location? This should trigger a flow where the game can't be found - but if eldenring.exe persists in that old location, the game directory would still be treated as valid and mapstudio will continue to look in that folder.
Are there any special permissions attached to regulation.bin preventing mapstudio being allowed to know if it exists? Does another process have the file open? Are you using linux?

I am closing this issue under the assumption it is the trivial case. If the game folder indicated by the project.json contains the regulation.bin file, please reopen and we can look for reasons why the .net runtime might be unable to find the file.
