### ISSUE TITLE
When i loading dark souls 3 m51 ringed city , DSMS crash.

### ISSUE THREAD

**Issue by colaaaaaa123** [soulsmods/DSMapStudio#910]
This is my log, maybe it will help you
DSMapStudio Version 1.11.0

Read Byte not present in enum: 0x19

   at SoulsFormats.BinaryReaderEx.ReadEnum[TEnum,TValue](Func`1 readValue, String valueFormat) in ./src/Andre/SoulsFormats/SoulsFormats/Util/BinaryReaderEx.cs:line 901
   at SoulsFormats.BinaryReaderEx.ReadEnum8[TEnum]() in ./src/Andre/SoulsFormats/SoulsFormats/Util/BinaryReaderEx.cs:line 914
   at SoulsFormats.MSB3.Part.Collision.ReadTypeData(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs:line 1407
   at SoulsFormats.MSB3.Part..ctor(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs:line 399
   at SoulsFormats.MSB3.Part.Collision..ctor(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs:line 1403
   at SoulsFormats.MSB3.PartsParam.ReadEntry(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs:line 141
   at SoulsFormats.MSB3.Param`1.Read(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/MSB3.cs:line 199
   at SoulsFormats.MSB3.Read(BinaryReaderEx br) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/MSB3.cs:line 104
   at SoulsFormats.SoulsFile`1.Read(String path) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SoulsFile.cs:line 87
   at StudioCore.MsbEditor.Universe.LoadMapAsync(String mapid, Boolean selectOnLoad) in ./src/StudioCore/MsbEditor/Universe.cs:line 745
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in ./src/StudioCore/MapStudioNew.cs:line 1346
   at StudioCore.MapStudioNew.Run() in ./src/StudioCore/MapStudioNew.cs:line 368
   at DSMapStudio.Program.Main(String[]) in ./src/Studio.App/DSMapStudio/Program.cs:line 36

thank you so much

**Comment by Philiquaz** [comment]
Looks like an incomplete enumeration of hitfiltertype slipped in when MSB classes were updated with annotations from vawser. I've posted a revert and it should be available immediately through github actions.
Thanks for the report.

**Comment by Philiquaz** [comment]
Merged a reversion of the problem change.
