### ISSUE TITLE
"Empty String" Crashing

### ISSUE THREAD

**Issue by Steuvan** [soulsmods/DSMapStudio#922]
I don't know if the update was supposed to fix this bug sooo I made a new post
Same log as before :

DSMapStudio Version 1.11.1

The value cannot be an empty string. (Parameter 'path')

   at System.ArgumentException.ThrowNullOrEmptyException(String, String)
   at System.ArgumentException.ThrowIfNullOrEmpty(String , String )
   at System.IO.File.WriteAllBytes(String, Byte[])
   at StudioCore.Editor.ProjectSettings.Serialize(String path) in ./src/StudioCore/Editor/ProjectSettings.cs:line 51
   at StudioCore.MapStudioNew.SaveAll() in ./src/StudioCore/MapStudioNew.cs:line 633
   at StudioCore.MapStudioNew.AttemptSaveOnCrash() in ./src/StudioCore/MapStudioNew.cs:line 666
   at DSMapStudio.Program.Main(String[]) in ./src/Studio.App/DSMapStudio/Program.cs:line 40

**Comment by randomUserNo** [comment]
I have the same issue and made a [thread](https://github.com/soulsmods/DSMapStudio/issues/957) myself.

Did you ever solve it?
