### ISSUE TITLE
DSMS crashing on start up

### ISSUE THREAD

**Issue by Leroswend** [soulsmods/DSMapStudio#935]
I am experiencing immediate crashing on start up, I have used UXM selective unpacker and followed all other instructions for DSMS, I am not sure what is causing the issue crash log is attached

[Log 2024-6-30--19-48-09.txt](https://github.com/user-attachments/files/16047154/Log.2024-6-30--19-48-09.txt)

**Comment by Philiquaz** [comment]
The former error message appears to be fallout from a different crash (likely unknown dcx type, and the last loaded project not being defined, so it very intelligently crashes when trying to save a backup)

The latter error message is likely appearing because you don't have the files unzipped, so it's failing to find the regular shader, and then failing again to find the backup shader.

**Comment by Leroswend** [comment]
How would I go about fixing an unknown dcx type? I've also just been unable to open a new project at all. Sorry if I'm coming across a bit dumb but I'm very new to using programs like dsms so just want some clarification on where things are going wrong.

**Comment by CreapyMushy** [comment]
anyone know of a fix??

**Comment by CreapyMushy** [comment]
anyone know when a fix is going to be released im pretty sure the dlc broke it somehow

**Comment by chrispysaid** [comment]
Getting a series of very cool errors when creating a new ER project:

```
Unknown DCX format.
at SoulsFormats.DCX.Decompress(BinaryReaderEx brt Type& type) in Jsrc/Andre/SoulsFormats/SoulsFormats/Formats/DCX.cs:line 159
at SoulsFormats.SFUtil.GetDecompressedBR(BinaryReaderEx brt Type& compression) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs.•line 212
at SoulsFormats.MountedSoulsFile'1.Read(Memory'1 bytes) in Jsrc/Andre/SoulsFormats/SoulsFormats/Util/MountedSoulsFile.cs:line 28
at SoulsFormats.SFUtil.DecryptERRegulation(String path) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 531
at StudioCore.ParamEditor.ParamBankSaveParamsER(Boolean partial) in Jsrc/StudioCore/ParamEditor/ParamBank.cs:line 1904
at StudioCore.ParamEditor.ParamBank.SaveParams(Boolean loose, Boolean partialParams) in ./src/StudioCore/ParamEditor/ParamBank.cs:line 2046
at StudioCore.ParamEditor.ParamEditorScreenSaveAllO in Jsrc/StudioCore/ParamEditor/ParamEditorScreen.cs:line 1178
```
```
Attempted to save project files to Engine 2\ModEngine-2.1 (09-47-28) for manual recovery.
You must manually replace your project files with these recovery files should you wish to restore them.
Given the program has crashed, these files may be corrupt and you should backup your last good saved
files before attempting to use these.
```
```
DSMapStudio has run into an issue.
Crash log has been generated at Engine Logs\Log 2024-7-10--21-49-11 .txt".
Crash Log:
DSMapStudio Version 1.11,1
Unknown DCX format.
at SoulsFormats.DCX.Decompress(BinaryReaderEx brt Type& type) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/DCX.cs:line 159
at SoulsFormatsSFUtil.GetDecompressedBR(BinaryReaderEx brt Type& compression) in Jsrc/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 212
at SoulsFormats.MountedSoulsFileS1.Read(Memory'1 bytes) in ./src/Andre/SoulsFormats/SoulsFormats/Util/MountedSoulsFile.cs:line 28
at SoulsFormatsSFUtil.DecryptERRegulation(String path) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 531
at StudioCore.ParamEditor.ParamBank.LoadParamsERFromFile(String path, Boolean encrypted) in ./src/StudioCore/ParamEditor/ParamBank.cs:line 952
at StudioCore.ParamEditor.ParamBank.LoadVParamsERO in ./src/StudioCore/ParamEditor/ParamBank.cs:line 933
at in ./src/StudioCore/ParamEditor/ParamBank.cs:line 1160
at StudioCore.Editor.TaskManager.LiveTask.< CreateTask> in ./src/StudioCore/Editor/TaskManager.cs:line 183
at System.Threading.Tasks.Task.lnnerlnvokeO
at System. Threading. Tasks. Task. < .cctor> b_281 _0(Object obj)
at System. Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
End of stack trace from previous location
at System. Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at System. Threading. Tasks. Task.ExecuteWithThreadLocal(Task&, Thread )
```

Thanks Kanye, very cool
