### ISSUE TITLE
Program instantly collapses after creating new project

### ISSUE THREAD

**Issue by LastMK** [soulsmods/DSMapStudio#948]
[Log 2024-8-31--22-01-01.txt](https://github.com/user-attachments/files/16825975/Log.2024-8-31--22-01-01.txt)

Here is the log but it tell absolutely nothing to me.

**Comment by celdorwow** [comment]
I have the same issue on creating a new project. After pointing at the project folder, game folder, and accepting to create a project, the app reports unrecognised DCX format and crashes. Here's the log:

```
DSMapStudio Version 1.11.1

Unknown DCX format.

   at SoulsFormats.DCX.Decompress(BinaryReaderEx br, Type& type) in ./src/Andre/SoulsFormats/SoulsFormats/Formats/DCX.cs:line 159
   at SoulsFormats.SFUtil.GetDecompressedBR(BinaryReaderEx br, Type& compression) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 212
   at SoulsFormats.MountedSoulsFile`1.Read(Memory`1 bytes) in ./src/Andre/SoulsFormats/SoulsFormats/Util/MountedSoulsFile.cs:line 28
   at SoulsFormats.SFUtil.DecryptERRegulation(String path) in ./src/Andre/SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 531
   at StudioCore.ParamEditor.ParamBank.LoadParamsERFromFile(String path, Boolean encrypted) in ./src/StudioCore/ParamEditor/ParamBank.cs:line 952
   at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in ./src/StudioCore/ParamEditor/ParamBank.cs:line 878
   at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass73_0.<ReloadParams>b__0() in ./src/StudioCore/ParamEditor/ParamBank.cs:line 1112
   at StudioCore.Editor.TaskManager.LiveTask.<CreateTask>b__15_0() in ./src/StudioCore/Editor/TaskManager.cs:line 183
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
```
