### ISSUE TITLE
DSMapStudio Crashing upon duplicating an enemy

### ISSUE THREAD

**Issue by devid-mazzaferro** [soulsmods/DSMapStudio#950]
As per title, DSMapStudio will crash if I try to duplicate an enemy of any kind, in any place of the map in DSR.

EDIT: this also appears to be happening upon doing Create -> Parts -> Enemy, but not for Objects
Downgrading to DSMapStudio 1.10.0 works fine.

Full Crash Log:

DSMapStudio Version 1.11.1

Value cannot be null. (Parameter 'destinationArray')

   at System.Array.Copy(Array, Array, Int32)
   at StudioCore.MsbEditor.Entity.DeepCopyObject(Object obj) in ./src/StudioCore/MsbEditor/Entity.cs:line 284
   at StudioCore.MsbEditor.Entity.Clone() in ./src/StudioCore/MsbEditor/Entity.cs:line 306
   at StudioCore.MsbEditor.MapEntity.Clone() in ./src/StudioCore/MsbEditor/Entity.cs:line 1458
   at StudioCore.MsbEditor.CloneMapObjectsAction.Execute() in ./src/StudioCore/MsbEditor/Action.cs:line 390
   at StudioCore.MsbEditor.ActionManager.ExecuteAction(Action a) in ./src/StudioCore/MsbEditor/ActionManager.cs:line 55
   at StudioCore.MsbEditor.MsbEditorScreen.OnGUI(String[] initcmd) in ./src/StudioCore/MsbEditor/MsbEditorScreen.cs:line 989
   at StudioCore.MapStudioNew.Update(Single deltaseconds) in ./src/StudioCore/MapStudioNew.cs:line 1343
   at StudioCore.MapStudioNew.Run() in ./src/StudioCore/MapStudioNew.cs:line 368
   at DSMapStudio.Program.Main(String[]) in ./src/Studio.App/DSMapStudio/Program.cs:line 36

**Comment by Geper23** [comment]
thank you 1.10.0 version is better for me now :)
